### ISSUE TITLE
Example doesn't output correct GIF

### ISSUE THREAD

**Issue by yaizudamashii** [ueman/screenrecorder#1]
image package's encodeGIF cannot encode transparent background, so all we get is a black square when we actually play the video.  Should I make a PR to make the background white? (or any non transparent color)

**Comment by ueman** [comment]
Which version oft he library are you using?
I thought I fixed that bug in 0.0.2

If that doesn't work you'll have to set the background yourself I guess.

Though please note that this library is in a really early state, so bugs and non working stuff is expected.

**Comment by faizanrafiq7** [comment]
still it is happending with the latest verion
seeing black box when we play the video

**Comment by ueman** [comment]
A temporary workaround is to set a background manually yourself.

I also accept PRs which fix this.

**Comment by mayaparamita** [comment]
Same, I get black box too and I don't know why

**Comment by ueman** [comment]
It's fixed in the latest version.
