### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by tenSunFree** [ueman/screenrecorder#11]
Continuous clicking on showRecodedVideo button gives error, null check operator used on a null value.
<img width="648" alt="002" src="https://user-images.githubusercontent.com/23090085/155164512-d3461569-2276-4191-84bd-ccefcd3e583a.png">

Mainly because the _frames is empty, which then results in gif being empty, Maybe try adding a null value judgment.
<img width="482" alt="003" src="https://user-images.githubusercontent.com/23090085/155165980-b3652f6b-f576-4a20-a2ff-f0881f8c9537.png">

**Comment by ueman** [comment]
Oh interesting, thanks for reporting.
