### ISSUE TITLE
Gif makes size 5-10x bigger?

### ISSUE THREAD

**Issue by fzyzcjy** [ueman/screenrecorder#12]
Hi thanks for the lib! I see it does not support mp4 but support gif, but seems that the size is usually 5-10x bigger. Thus I wonder what to do to support mp4?

Or, can we use webp?

**Comment by ueman** [comment]
This library is a pure Dart/Flutter library, and it should stay that way. It's also still pretty beta quality.

However, you can use https://pub.dev/packages/flutter_ffmpeg to convert the GIF to mp4 after the export finished. I intend to make the exporter configurable in the future, but I don't have as much time to work on this as I would like.

If you want to open a PR for that, I would appreciate it.

**Comment by ueman** [comment]
I've just added support to write and use custom exporters. I won't support any exporter which makes use of native stuff directly in the library, but I'm happy to add those to the example. So if you happen to write one, feel free to create a PR which adds it to the example.

Therefore, I'll close this issue.
