### ISSUE TITLE
How to convert to MP4

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [ueman/screenrecorder#14]

**Comment by nguyenleanhkhoa** [comment]
I want to convert to Mp4 file

**Comment by ueman** [comment]
This library does not support converting screen recordings, so you have to use one of the available converter tools on pub.dev

**Comment by AkaankshK** [comment]
@ueman Can you please suggest one converter plugin

**Comment by AkaankshK** [comment]
@ueman Thank you for the plugin. Can you please help me with a sample code for mp4 conversion

**Comment by ueman** [comment]
> @ueman Thank you for the plugin. Can you please help me with a sample code for mp4 conversion

No, since I'm not doing that myself I would have to look it up myself. I'm sure you will find a way 👍
