### ISSUE TITLE
Proposal: make Exporter dynamic

### ISSUE THREAD

**Issue by omartinma** [ueman/screenrecorder#18]
First, thanks for creating this package ;)

I wanted to propose a change to the API for Exporter. The current API is really coupled to export a GIF(or any composition resulting in List<int>). In my use case for example I will not need a List<int> since my plan is to send to a backend the frames captured by the recorded. So something like this will be sufficient for me:

````dart
class FramesExporter implements Exporter {
  final List<Frame> _frames = [];
  @override
  void onNewFrame(Frame frame) {
    _frames.add(frame);
  }

  @override
  Future<List<ByteData>> export() async {
    final images = <ByteData>[];
    for (final frame in _frames) {
      final bytes =
          await frame.image.toByteData(format: ui.ImageByteFormat.png);
      if (bytes != null) {
        images.add(bytes);
      } else {
        print('Skipped frame while enconding');
      }
    }
    return images;
  }
}
````

This can be achieved by changing the Exporter class to:

```dart
abstract class Exporter {
  void onNewFrame(Frame frame);
  Future export();
}
```

And that way your current GifExporter is not affected and there is not any breaking change. Let me know if you are ok with this and I can create a PR since I already have a branch with the changes also adding a new example where instead of exporting a GIF simply display in a ListView the frames captured.

Thanks!

**Comment by ueman** [comment]
> First, thanks for creating this package ;)

Thank you very much!

> And that way your current GifExporter is not affected and there is not any breaking change. Let me know if you are ok with this and I can create a PR since I already have a branch with the changes also adding a new example where instead of exporting a GIF simply display in a ListView the frames captured.

Sounds good, I'll happily accept it

**Comment by ueman** [comment]
@omartinma
Actually, now that I think about it, what do you think of generics?

```dart
ScreenRecorder<T>(
  height: 200,
  width: 200,
  background: Colors.white,
  controller: ScreenRecorderController<T>(
    pixelRatio: 0.5,
    skipFramesBetweenCaptures: 2,
  ),
  child: // child which should be recorded
);

ScreenRecorderController.export<T>();

class Exporter<T> {
//...
}
```

Then the default constructor takes a generic and `ScreenRecorder.gif` is for gifs.

Does that make sense to you?

**Comment by omartinma** [comment]
> @omartinma Actually, now that I think about it, what do you think of generics?
> 
> ```dart
> ScreenRecorder<T>(
>   height: 200,
>   width: 200,
>   background: Colors.white,
>   controller: ScreenRecorderController<T>(
>     pixelRatio: 0.5,
>     skipFramesBetweenCaptures: 2,
>   ),
>   child: // child which should be recorded
> );
> 
> ScreenRecorderController.export<T>();
> 
> class Exporter<T> {
> //...
> }
> ```
> 
> Then the default constructor takes a generic and `ScreenRecorder.gif` is for gifs.
> 
> Does that make sense to you?

Actually, I just thought about another problem. What about if anyone wants to export frames and gifs? With the current approach would be impossible to achieve, or you will need 2 controllers for that.

**Comment by omartinma** [comment]
What about simplify like this? @ueman 
```dart
import 'dart:ui' as ui show ImageByteFormat;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image/image.dart' as image;
import 'package:screen_recorder/src/frame.dart';

class Exporter {
  final List<Frame> _frames = [];
  void onNewFrame(Frame frame) {
    _frames.add(frame);
  }

  Future<List<RawFrame>?> exportFrames() async {
    if (_frames.isEmpty) {
      return null;
    }
    final bytesImages = <RawFrame>[];
    for (final frame in _frames) {
      final bytesImage =
          await frame.image.toByteData(format: ui.ImageByteFormat.png);
      if (bytesImage != null) {
        bytesImages.add(RawFrame(16, bytesImage));
      } else {
        print('Skipped frame while enconding');
      }
    }
    return bytesImages;
  }

  Future<List<int>?> exportGif() async {
    final frames = await exportFrames();
    if (frames == null) {
      return null;
    }
    final result = compute(_exportGif, frames);
    _frames.clear();
    return result;
  }

  static Future<List<int>?> _exportGif(List<RawFrame> frames) async {
    final animation = image.Animation();
    animation.backgroundColor = Colors.transparent.value;
    for (final frame in frames) {
      final iAsBytes = frame.image.buffer.asUint8List();
      final decodedImage = image.decodePng(iAsBytes);

      if (decodedImage == null) {
        print('Skipped frame while enconding');
        continue;
      }
      decodedImage.duration = frame.durationInMillis;
      animation.addFrame(decodedImage);
    }
    return image.encodeGifAnimation(animation);
  }
}

class RawFrame {
  RawFrame(this.durationInMillis, this.image);

  final int durationInMillis;
  final ByteData image;
}

```

**Comment by omartinma** [comment]
I just created this Draft PR maybe we can continue there

https://github.com/ueman/screenrecorder/pull/19
