### ISSUE TITLE
exportFrame takes a very long time to get the result

### ISSUE THREAD

**Issue by MirzaIkhsan** [ueman/screenrecorder#22]
Hey, I think this package is awesome, I used it in my app. 
But there is problem when I set the pixelRatio to 3 it will take a very long time to generate the frames.

I use this package to record the widget and then use the frames to make a video. But it will become a problem if it takes a very long time to generate the frames.

Thanks

**Comment by ueman** [comment]
Then don't set the pixel ratio to 3. Raising the quality increases the processing time since there's more data. I can't change that 😅

If you do have any actionable ideas on how to improve this package, I would greatly appreciate a contribution via PR.
