### ISSUE TITLE
error output from screen_recorder 0.2.0 which is not able to import

### ISSUE THREAD

**Issue by khemmanat** [ueman/screenrecorder#25]
Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.
pub get failed (1; Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.)
exit code 1

**Comment by khemmanat** [comment]
@ueman  I want to import the latest version of screen_recorder (0.2.0) into my project so that when I make a pub get in my project. Then this happen to my terminal response:
`Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.
pub get failed (1; Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.)
exit code 1`
So how can I use screen_recorder package of the latest version.

**Comment by MirzaIkhsan** [comment]
> @ueman I want to import the latest version of screen_recorder (0.2.0) into my project so that when I make a pub get in my project. Then this happen to my terminal response: `Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed. pub get failed (1; Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.) exit code 1` So how can I use screen_recorder package of the latest version.

I'm fixed it by change the flutter channel from stable to beta version. It seems that this package haven't support for the stable version.

**Comment by khemmanat** [comment]
> > @ueman I want to import the latest version of screen_recorder (0.2.0) into my project so that when I make a pub get in my project. Then this happen to my terminal response: `Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed. pub get failed (1; Because video_cap_com_test depends on screen_recorder >=0.1.0 which requires Flutter SDK version >=3.4.0-34.1.pre, version solving failed.) exit code 1` So how can I use screen_recorder package of the latest version.
> 
> I'm fixed it by change the flutter channel from stable to beta version. It seems that this package haven't support for the stable version.

Ahh yeah this is what I'm meaning to say that I want use in the stable version.
