### ISSUE TITLE
The height is uncertain, with white edges above and below

### ISSUE THREAD

**Issue by tudosxxx** [ueman/screenrecorder#26]
1.The height is uncertain, with white edges above and below

`

Container(
            width: Get.width,
            height: Get.height,
            color: Colors.black,
            child: Center(
              child: ScreenRecorder(
                controller: screenRecorderController,
                width: uiImage.width.toDouble(),
                height: uiImage.height.toDouble(),
                child: Stack(
                  children: [
                    Center(
                      child: Image.file(widget.file,width: uiImage.width.toDouble(),height: uiImage.height.toDouble(),),
                    ),
                    Positioned(
                      top: y,
                      left: x,
                      child: GestureDetector(
                        onPanUpdate: (DragUpdateDetails e) {
                          setState(() {
                            x += e.delta.dx;
                            y += e.delta.dy;
                          });
                        },
                        onPanEnd: (DragEndDetails e){
                          print(e.velocity);
                        },
                        child: Text(widget.text,style: TextStyle(color: Colors.red,fontSize: 30),),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          )

`

**Comment by tudosxxx** [comment]
![cs](https://user-images.githubusercontent.com/52568890/209527315-2ec80334-0525-4a42-b9a0-b049d0dd5f8c.gif)

**Comment by tudosxxx** [comment]
When recording this gif, the speed will increase, the height will have white edges, and the width will decrease

**Comment by tudosxxx** [comment]
Gif Add Text

**Comment by tudosxxx** [comment]
gif add text。 When recording this gif, the speed will increase, the height will have white edges。

**Comment by tudosxxx** [comment]
https://user-images.githubusercontent.com/52568890/209527885-357173bc-41b0-4da3-bd55-a861574fc844.mp4

**Comment by tudosxxx** [comment]
![hello](https://user-images.githubusercontent.com/52568890/209529169-7a4b1a84-1fa8-4457-bb3b-706fc98b3f1e.gif)

**Comment by ueman** [comment]
I have a hard time understanding what exactly your asking for or what your issue is. Can you please explain your issue in more detail?

**Comment by tudosxxx** [comment]
fit: BoxFit.cover  now，I can fill it with this attribute.Can I leave the width and height unlocked? Make sure it will not change during recording.

**Comment by ueman** [comment]
> Can I leave the width and height unlocked?

Sure, if that's what you want.

> Make sure it will not change during recording

That's something you have to enforce. I don't don't know what will happen if it changes during recording though.

In general, you have to enforce the size of the recording. The white borders come because that's what you're recording. If you don't want them, change the layout.

**Comment by tudosxxx** [comment]
It is too slow to generate files. Is there a solution? Or can you provide a view display first?

**Comment by ueman** [comment]
> It is too slow to generate files.

Yep, I know.

> Is there a solution? 

I've prototyped a bit at https://github.com/ueman/screenrecorder/pull/21, feel free to improve on that. I currently don't have time to work on it. If you happen to work on it, I would greatly appreciate a PR.
