### ISSUE TITLE
 Add audio to screen recording and export as video

### ISSUE THREAD

**Issue by Lix-ai** [ueman/screenrecorder#4]
Add audio to screen recording and export as video
:)

**Comment by ueman** [comment]
This package is intended as a pure Dart implementation and Flutter does not allow audio recording. There's also no package that I know of that allows encoding of videos in pure Dart.

So this is not and probably will never be possible. 

However there's nothing stopping you from using [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg) or [flutter_video_compress](https://pub.dev/packages/flutter_video_compress) for example to encode the gif as a video.
