### ISSUE TITLE
Not an Issue, just a suggestion.

### ISSUE THREAD

**Issue by NeilCaffrey1** [ueman/screenrecorder#6]
Very impressive.

Can we the run the export on a seperate isolate to speed things up?

**Comment by ueman** [comment]
Yeah, but it wouldn't help much because `image` is single threaded. So it would just take as much time on another thread. Also isolates are dart:io only so it won't help on web.

**Comment by ueman** [comment]
At the moment you can only speed it up by reducing the quality. I plan to make transcoding changeable so you could use ffmpeg on mobile but there's no timeline yet

**Comment by NeilCaffrey1** [comment]
Thank you for the speedy reply. I appreciate it.
