### ISSUE TITLE
latest flutter sdk complains, and also, workaround provides black result

### ISSUE THREAD

**Issue by jeffreyliu8** [ueman/screenrecorder#8]
![Screen Shot 2021-08-25 at 11 22 47 AM](https://user-images.githubusercontent.com/12398645/130844814-1b84047e-9573-49f2-9c7d-4d579fc6d181.png)
<img width="912" alt="Screen Shot 2021-08-25 at 11 22 37 AM" src="https://user-images.githubusercontent.com/12398645/130844823-615a356c-a1c5-48e6-8587-19d4a9420431.png">

**Comment by ueman** [comment]
This is now fixed
